baseURL = '/site/'
languageCode = 'en-us'
title = 'My Site'
theme = "shibui"

relativeURLs = true

[params]
  author = "Ghania"
  email = "your.email@example.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
